server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Cl@v3S3gur@
    url: jdbc:postgresql://localhost:5432/postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
